package reqtype

import "gitlab.com/evatix-go/core/coreimpl/enumimpl"

var (
	Ranges = [...]string{
		Uninitialized:                    "Uninitialized",
		Create:                           "Create",
		Read:                             "Read",
		Update:                           "Update",
		Delete:                           "Delete",
		Drop:                             "Drop",
		CreateOrUpdate:                   "CreateOrUpdate",
		ExistCheck:                       "ExistCheck",
		SkipOnExist:                      "SkipOnExist",
		CreateOrSkipOnExist:              "CreateOrSkipOnExist",
		UpdateOrSkipOnNonExist:           "UpdateOrSkipOnNonExist",
		DeleteOrSkipOnNonExist:           "DeleteOrSkipOnNonExist",
		DropOrSkipOnNonExist:             "DropOrSkipOnNonExist",
		UpdateOnExist:                    "UpdateOnExist",
		DropOnExist:                      "DropOnExist",
		DropCreate:                       "DropCreate",
		Append:                           "Append",
		AppendByCompare:                  "AppendByCompare",
		AppendByCompareWhereCommentFound: "AppendByCompareWhereCommentFound",
		AppendLinesByCompare:             "AppendLinesByCompare",
		AppendLines:                      "AppendLines",
		CreateOrAppend:                   "CreateOrAppend",
		Prepend:                          "Prepend",
		CreateOrPrepend:                  "CreateOrPrepend",
		PrependLines:                     "PrependLines",
		Rename:                           "Rename",
		Change:                           "Change",
		Merge:                            "Merge",
		MergeLines:                       "MergeLines",
		GetHttp:                          "GetHttp",
		PutHttp:                          "PutHttp",
		PostHttp:                         "PostHttp",
		DeleteHttp:                       "DeleteHttp",
		PatchHttp:                        "PatchHttp",
		Touch:                            "Touch",
		InheritOnly:                      "InheritOnly",
		InheritPlusOverride:              "InheritPlusOverride",
		DynamicAction:                    "DynamicAction",
	}

	RangesMap = map[string]Request{
		"Uninitialized":                    Uninitialized,
		"Create":                           Create,
		"Read":                             Read,
		"Update":                           Update,
		"Delete":                           Delete,
		"Drop":                             Drop,
		"CreateOrUpdate":                   CreateOrUpdate,
		"ExistCheck":                       ExistCheck,
		"SkipOnExist":                      SkipOnExist,
		"CreateOrSkipOnExist":              CreateOrSkipOnExist,
		"UpdateOrSkipOnNonExist":           UpdateOrSkipOnNonExist,
		"DeleteOrSkipOnNonExist":           DeleteOrSkipOnNonExist,
		"DropOrSkipOnNonExist":             DropOrSkipOnNonExist,
		"UpdateOnExist":                    UpdateOnExist,
		"DropOnExist":                      DropOnExist,
		"DropCreate":                       DropCreate,
		"Append":                           Append,
		"AppendByCompare":                  AppendByCompare,
		"AppendByCompareWhereCommentFound": AppendByCompareWhereCommentFound,
		"AppendLinesByCompare":             AppendLinesByCompare,
		"AppendLines":                      AppendLines,
		"CreateOrAppend":                   CreateOrAppend,
		"Prepend":                          Prepend,
		"CreateOrPrepend":                  CreateOrPrepend,
		"PrependLines":                     PrependLines,
		"Rename":                           Rename,
		"Change":                           Change,
		"Merge":                            Merge,
		"MergeLines":                       MergeLines,
		"GetHttp":                          GetHttp,
		"PutHttp":                          PutHttp,
		"PostHttp":                         PostHttp,
		"DeleteHttp":                       DeleteHttp,
		"PatchHttp":                        PatchHttp,
		"Touch":                            Touch,
		"InheritOnly":                      InheritOnly,
		"InheritPlusOverride":              InheritPlusOverride,
		"DynamicAction":                    DynamicAction,
	}

	BasicEnumImpl = enumimpl.NewBasicByteUsingIndexedSlice(Ranges[:])
)
